version: '2'

services:
  openai-relay:
    build:
      context: .
      dockerfile: Dockerfile
    image: openai-relay:latest
    container_name: openai-relay
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 8080
      NODE_ENV: ${NODE_ENV}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    volumes:
      - ./logs:/app/logs
    mem_limit: 512m
    memswap_limit: 512m
    cpu_shares: 512


