-- Art Gallery - Grouped Grid Mode (Digital Access)
-- Template: Contemporary Art Exhibition with categories by medium
-- 
-- INSTRUCTIONS:
-- 1. Replace 'YOUR_USER_ID_HERE' with actual user UUID
-- 2. Update image_url values with actual uploaded image URLs
-- 3. Run this SQL in Supabase SQL Editor or via psql

DO $body$
DECLARE
    v_user_id UUID := 'YOUR_USER_ID_HERE'::UUID;
    v_card_id UUID;
    v_cat_paintings UUID;
    v_cat_sculptures UUID;
    v_cat_digital UUID;
    v_cat_installations UUID;
BEGIN
    -- Insert the card
    INSERT INTO cards (
        id, user_id, name, description, content_mode, is_grouped, group_display, billing_type,
        conversation_ai_enabled, ai_instruction, ai_knowledge_base,
        ai_welcome_general, ai_welcome_item, image_url,
        is_access_enabled, access_token
    ) VALUES (
        gen_random_uuid(),
        v_user_id,
        'Modern Visions: Contemporary Art Collection',
        E'Welcome to **Modern Visions**, featuring 12 groundbreaking contemporary artworks that challenge perception and celebrate human creativity.\n\nThis exhibition brings together emerging and established artists exploring themes of identity, technology, and the natural world through painting, sculpture, and mixed media.\n\n🎨 Tap any artwork to learn more and chat with our AI art guide.',
        'grid',
        true,
        'expanded',
        'digital',
        true,
        'You are an enthusiastic art docent at a contemporary art gallery. Speak with passion about the artworks, artists, and artistic movements. Help visitors understand the meaning, techniques, and context behind each piece. Be approachable and encourage questions. Avoid overly academic language.',
        E'Modern Visions Exhibition - Contemporary Art Collection 2024\n\nExhibition themes: Identity in the digital age, environmental consciousness, urban life, human connection, abstraction and emotion.\n\nGallery layout: Main hall (large installations), East wing (paintings), West wing (sculptures and mixed media), North gallery (digital art).\n\nCurator: Dr. Helena Vance, former MoMA associate curator\nCollection value: Insured for $12 million\n\nArtist talks every Saturday at 2pm. Guided tours at 11am and 3pm daily.\nGift shop near exit with exhibition catalog ($45) and prints available.\nPhotography allowed without flash. No touching artworks.\nAudio guide available: $8 rental or free via gallery app.',
        'Welcome to Modern Visions! I can tell you about any artwork''s meaning, the artist''s story, techniques used, or suggest what to see based on your interests. What draws your attention?',
        'This is "{name}" - I can share the artist''s inspiration, explain the technique, give historical context, or connect it to other works here. What interests you?',
        NULL,
        TRUE,
        replace(replace(encode(gen_random_bytes(9), 'base64'), '+', '-'), '/', '_')
    ) RETURNING id INTO v_card_id;

    -- Create categories by medium (Layer 1)
    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '🖼️ Paintings', E'Traditional and contemporary painting techniques exploring color, form, and emotion.\n\n📍 **East Wing** | 5 works', 'The Paintings section features works in oil, acrylic, and mixed media on canvas. Located in the East Wing with natural north-facing light optimal for viewing. Temperature maintained at 21°C with 45% humidity for preservation.', 1)
    RETURNING id INTO v_cat_paintings;

    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '🗿 Sculptures', E'Three-dimensional works exploring space, form, and material.\n\n📍 **West Wing** | 4 works', 'The Sculptures section showcases works in bronze, glass, steel, and found materials. West Wing has 5-meter ceilings to accommodate large pieces. Touch-free viewing only.', 2)
    RETURNING id INTO v_cat_sculptures;

    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '💻 Digital Art', E'Technology-driven and generative works at the intersection of art and code.\n\n📍 **North Gallery** | 3 works', 'Digital Art section features projection mapping, AI-generated art, and interactive installations. Darkened gallery space with controlled viewing environment. Some works respond to viewer movement.', 3)
    RETURNING id INTO v_cat_digital;

    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '🏛️ Installations', E'Large-scale immersive experiences that transform the gallery space.\n\n📍 **Main Hall** | 3 works', 'Installations section features room-scale works in the Main Hall. Allow 10-15 minutes per installation for full experience. Some works have timed entry.', 4)
    RETURNING id INTO v_cat_installations;

    -- Insert paintings (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_paintings, 'Echoes of Tomorrow', E'**Artist:** Maya Chen (b. 1988, Taipei)\n**Year:** 2024\n**Medium:** Oil on canvas, embedded LED elements\n**Dimensions:** 180 × 240 cm\n\n---\n\nA stunning fusion of traditional oil painting with embedded LED lighting, this piece depicts a cityscape that shifts between day and night. The LEDs are programmed to cycle through a 24-hour light pattern, transforming the artwork continuously.\n\nChen explores how technology shapes our perception of urban spaces and the passage of time—questioning whether we control technology or it controls us.\n\n*"I wanted to capture that moment between waking and dreaming, when the city exists in both states simultaneously."* — Maya Chen\n\n---\n\n🏆 **Awarded:** Art Basel Emerging Artist Prize 2024\n💡 **Note:** Best viewed during the 8-minute sunset cycle (every 2 hours)', NULL, 'Maya Chen studied at RISD and Central Saint Martins. Known for incorporating technology into traditional painting. This piece took 8 months to complete - 4 months painting, 4 months electronic integration. LEDs are museum-grade with 100,000-hour lifespan. The work was featured on the cover of Art Forum. Chen was inspired by her childhood in Taipei''s night markets contrasted with her later life in smart cities. Currently represented by Gagosian Gallery.', 1),
    
    (v_card_id, v_cat_paintings, 'Concrete Dreams', E'**Artist:** Fatima Al-Hassan (b. 1985, Beirut)\n**Year:** 2024\n**Medium:** Concrete, embedded photographs, archival resin\n**Dimensions:** 90 × 120 cm (triptych, 3 panels)\n\n---\n\nA deeply personal triptych embedding family photographs within concrete slabs. The photos gradually become visible as light passes through the semi-translucent resin pockets, creating a meditation on memory, permanence, and loss.\n\nThe concrete represents the buildings of Al-Hassan''s childhood neighborhood in Beirut, many of which no longer exist. The photographs are from her grandmother''s collection, spanning three generations.\n\n*"Memory is not fixed like concrete. It shifts, fades, and sometimes disappears entirely."* — Fatima Al-Hassan\n\n---\n\n📖 **Featured in:** "Women Artists of the Middle East" (Thames & Hudson, 2024)', NULL, 'Fatima Al-Hassan explores memory and displacement through mixed media. The concrete was sourced from demolished buildings in Beirut. Each photograph was protected with archival resin rated for 200+ years before embedding. Each panel took 3 months to cure properly. Al-Hassan''s family left Beirut during the civil war - this work processes intergenerational trauma. She splits time between Paris and Beirut. The technique she developed is now being studied by conservation specialists.', 2),
    
    (v_card_id, v_cat_paintings, 'Neon Wilderness', E'**Artist:** Tommy Rivera (b. 1990, Mexico City)\n**Year:** 2024\n**Medium:** Dead tree branches, custom neon tubes, electronics\n**Dimensions:** 300 × 400 × 200 cm\n\n---\n\nA forest of dead tree branches illuminated with custom neon tubes in blues, pinks, and purples. The installation explores the intersection of nature and artificiality, creating a surreal landscape that feels both familiar and alien.\n\nThe colors cycle through a 12-hour pattern representing a compressed day/night cycle. Sensors detect viewer proximity, causing subtle color shifts.\n\n*"We''re creating a world where nature is something we see through screens. This is what a forest looks like when it''s been filtered through Instagram."* — Tommy Rivera\n\n---\n\n⚡ **Technical:** Uses 2.4 kW of power, equivalent to a small refrigerator\n🌳 **Environmental note:** All branches collected from naturally fallen trees in Central Park', NULL, 'Tommy Rivera works with light and natural materials. Based in Brooklyn, trained in both fine art and electrical engineering. Branches collected from fallen trees in Central Park over 2 years with NYC Parks permission. Neon tubes custom-bent by artisans in Brooklyn''s last remaining neon shop. The work comments on how we experience nature through technology. Rivera''s Instagram following (800K) has made him one of the most followed contemporary artists. Color palette inspired by the Sonoran Desert at dusk meets urban nightlife.', 3),
    
    (v_card_id, v_cat_paintings, 'Urban Pulse', E'**Artist:** Kenji Watanabe (b. 1982, Tokyo)\n**Year:** 2023\n**Medium:** Acrylic on canvas with sound sensors\n**Dimensions:** 200 × 300 cm\n\n---\n\nA large-scale abstract work that visualizes the rhythm of city life. Hidden sensors detect ambient sound, causing sections of UV-reactive paint to subtly glow in response to conversation and movement.\n\nWatanabe spent a year recording sounds from Tokyo''s busiest intersections. The painting''s composition maps the frequency patterns of urban noise.\n\n*"Cities have heartbeats. I wanted to make that visible."* — Kenji Watanabe\n\n---\n\n🔊 **Interactive:** Speak near the painting and watch it respond\n🌙 **Best viewed:** Gallery dims lights every 30 minutes for UV effect', NULL, 'Kenji Watanabe bridges traditional Japanese painting techniques with electronic art. Trained in nihonga (traditional Japanese painting) before studying at MIT Media Lab. Sound recordings from Shibuya Crossing, Shinjuku Station, and Ginza. UV-reactive pigments are archival-grade, will remain reactive for 50+ years. The work was commissioned by the Japan Foundation. Watanabe''s previous work is in the permanent collection of the Mori Art Museum.', 4);

    -- Insert sculptures (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_sculptures, 'Fragments of Self', E'**Artist:** James Okonkwo (b. 1975, Lagos)\n**Year:** 2023\n**Medium:** Recycled mirrors, steel frame\n**Dimensions:** 200 × 150 × 150 cm\n\n---\n\nA sculptural installation using 847 recycled mirror fragments arranged to create a fragmented human figure. As viewers move around the piece, they see their own reflection broken and reassembled, questioning the nature of identity and wholeness.\n\nThe mirrors were collected from demolished buildings in London over 3 years—each fragment carries its own history of reflection.\n\n*"We are all made of fragments—experiences, memories, cultures. The illusion of a unified self is just that: an illusion."* — James Okonkwo\n\n---\n\n🏆 **Turner Prize Winner 2023**\n📍 **Viewing tip:** Walk slowly around the piece for the full effect', NULL, 'James Okonkwo explores identity and diaspora through sculpture. Born in Lagos, moved to London at 12, educated at Royal College of Art. Each mirror fragment represents a piece of cultural identity in the diaspora experience. Turner Prize jury cited "profound meditation on identity in an age of fragmentation." The work weighs 180kg and required custom installation. Okonkwo''s previous major work is in Tate Modern''s permanent collection. The piece has been acquired by the gallery for £350,000.', 1),
    
    (v_card_id, v_cat_sculptures, 'The Weight of Water', E'**Artist:** David Park (b. 1980, Seoul)\n**Year:** 2023\n**Medium:** Hand-cast glass droplets, suspended steel cables\n**Dimensions:** 400 × 300 × 250 cm (suspended from 5m height)\n\n---\n\nTwelve thousand hand-cast glass droplets suspended from the ceiling, creating an ethereal rain frozen in time. The installation represents the fragility of water resources and the impermanence of our natural world.\n\nEach droplet was individually cast over 18 months using Venetian glassblowing techniques combined with Korean metalwork traditions.\n\n*"We take water for granted until it''s gone. This piece asks: what if we could see every drop we waste, frozen in the air?"* — David Park\n\n---\n\n⚠️ **Conservation:** Please do not touch—oils from skin can damage glass\n💧 **Context:** Created in response to the 2022 global water crisis', NULL, 'David Park is known for large-scale glass installations addressing environmental themes. Trained in Venice with master glassblowers before returning to Seoul. Each of the 12,000 droplets took 3-5 minutes to create. Total weight of installation is 1.2 tonnes, supported by engineered ceiling structure. The piece was inspired by Park''s visit to drought-affected communities in California. A portion of sales proceeds goes to Water.org. Previously exhibited at the Venice Biennale where it won the Golden Lion.', 2),
    
    (v_card_id, v_cat_sculptures, 'The Listener', E'**Artist:** Roberto Gómez (b. 1972, Buenos Aires)\n**Year:** 2024\n**Medium:** Bronze, integrated sound installation\n**Dimensions:** 180 cm tall\n\n---\n\nA bronze figure with an oversized ear, housing concealed speakers that play ambient sounds recorded from public spaces around the world. The sculpture invites contemplation of how we listen—and what we choose to hear.\n\nSounds were recorded in 47 cities over 5 years: markets, protests, celebrations, everyday conversations in languages you may not understand.\n\n*"Listening is a political act. What we choose to hear shapes who we become."* — Roberto Gómez\n\n---\n\n🎧 **Audio loops:** 4 hours before repeating\n🗺️ **Sound locations:** Buenos Aires, Tokyo, Lagos, Berlin, Mumbai, and 42 more cities', NULL, 'Roberto Gómez creates sculptures with integrated sound, exploring themes of surveillance, communication, and global citizenship. Cast using traditional lost-wax method - the figure is solid bronze weighing 340kg. Sounds include: Buenos Aires street protests, Tokyo fish market at dawn, Berlin techno clubs, Mumbai street vendors. Audio system concealed in the base with museum-grade speakers. Gómez was inspired by his own experience as an immigrant, learning to listen in unfamiliar cities. Commissioned by the Serpentine Gallery in 2022.', 3),
    
    (v_card_id, v_cat_sculptures, 'Metamorphosis', E'**Artist:** Elena Kowalski (b. 1995, Warsaw)\n**Year:** 2024\n**Medium:** 3D-printed biodegradable PLA, living moss\n**Dimensions:** 120 × 80 × 80 cm\n\n---\n\nA geometric sculpture that deliberately transforms over time as living moss grows across its 3D-printed lattice structure. Over the exhibition''s run, the stark white form will become increasingly green.\n\nThe piece challenges notions of permanence in art—embracing change and natural processes as integral to the work.\n\n*"Traditional sculpture fights decay. I collaborate with it."* — Elena Kowalski\n\n---\n\n🌱 **Living art:** The moss is watered daily by gallery staff\n📅 **Watch it change:** Progress photos posted weekly on gallery Instagram', NULL, 'Elena Kowalski is one of the youngest artists in the exhibition. MFA from Central Saint Martins. The 3D-printed structure uses biodegradable PLA that will break down over 10 years. Moss species selected for indoor growth without direct sunlight. The work evolves throughout the exhibition—visitors are encouraged to return. Kowalski''s practice focuses on sustainability and impermanence. Previous work installed at the V&A as part of their "Future of Fashion" exhibition. She maintains a research partnership with materials scientists at Imperial College.', 4);

    -- Insert digital art (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_digital, 'Digital Garden #7', E'**Artist:** Sofia Andersson (b. 1992, Stockholm)\n**Year:** 2024\n**Medium:** Custom AI, projection mapping, motion sensors\n**Dimensions:** Variable (room-scale installation)\n\n---\n\nAn immersive digital environment where AI-generated flowers bloom and wilt in response to viewers'' movements. The algorithm creates unique botanical forms that have never existed in nature—each one generated and then lost forever.\n\nAndersson trained her own neural network on 2 million botanical images, teaching it to imagine impossible flowers.\n\n*"These flowers exist only in the moment of observation. Like memories, they cannot be preserved."* — Sofia Andersson\n\n---\n\n🤖 **AI:** Custom neural network trained on 2M botanical images\n👀 **Interactive:** Your movement influences which flowers bloom\n⏱️ **Each flower:** Exists for only 30-60 seconds', NULL, 'Sofia Andersson specializes in AI-generated art, bridging computer science and fine art. PhD in computational creativity from KTH Royal Institute of Technology. Each flower is unique—the algorithm has generated over 50 million unique forms since 2022. The installation uses 6 4K projectors and infrared motion sensors. Floor sensors detect up to 30 visitors simultaneously. Previous version shown at Ars Electronica where it won the Golden Nica. Andersson publishes her code as open source—her GitHub has 45K followers.', 1),
    
    (v_card_id, v_cat_digital, 'Binary Sunset', E'**Artist:** Alex Zhang-Müller (b. 1995, Berlin)\n**Year:** 2024\n**Medium:** Real-time data visualization, custom software, dual 4K screens\n**Dimensions:** 180 × 240 cm (each screen)\n\n---\n\nTwo screens display real-time sunsets from opposite sides of the Earth, visualized through abstract data patterns. As the sun sets in New Zealand, it rises in Portugal—the piece connects these distant moments through live weather data.\n\nThe visualization transforms atmospheric measurements (temperature, humidity, air quality) into flowing abstract forms.\n\n*"Distance is a construct. Right now, someone on the other side of the world is watching the same sun."* — Alex Zhang-Müller\n\n---\n\n🌍 **Live data:** Weather stations in Auckland, NZ and Lisbon, Portugal\n☀️ **Best viewing:** During actual sunset/sunrise times (check gallery schedule)\n📡 **Technical:** Runs 24/7, constantly changing', NULL, 'Alex Zhang-Müller works with data as artistic medium. Dual German-Chinese heritage informs work about connection across distance. Parents live in different countries—this piece began as a way to share experiences with them. Live data feeds from meteorological stations, processed through custom software. The work requires internet connection and crashes if either station goes offline (intentional—reflects fragility of connection). New media art collection at ZKM has acquired earlier version for permanent collection. Zhang-Müller maintains a Patreon with 2,000 supporters who receive daily data-art postcards.', 2),
    
    (v_card_id, v_cat_digital, 'Memory Palace', E'**Artist:** Priya Sharma (b. 1988, Mumbai)\n**Year:** 2024\n**Medium:** VR experience, haptic feedback, scent diffusion\n**Dimensions:** 3 × 3 meter viewing space\n\n---\n\nA virtual reality experience that reconstructs memories submitted by the public. Visitors wear VR headsets and haptic gloves to walk through a palace built from strangers'' recollections—wedding days, childhood homes, moments of loss.\n\nOver 500 memories were collected and recreated, with ambient scents triggered to match (ocean, flowers, rain).\n\n*"Memory is architecture. We all live in palaces we can never fully return to."* — Priya Sharma\n\n---\n\n⏱️ **Duration:** 12-minute experience\n👤 **Capacity:** 1 visitor at a time\n🎫 **Timed entry:** Book at gallery desk (included in admission)', NULL, 'Priya Sharma creates immersive experiences exploring collective memory. Background in architecture before transitioning to digital art. The 500 memories were collected through public call-out—participants were interviewed about their most vivid recollections. Scent machine uses essential oils selected by a perfumer. Haptic gloves provide touch sensation when "touching" objects in memory. The project took 3 years and involved 20 collaborators. Shown at Sundance New Frontier and won the Jury Prize. Sharma is working on a version that will eventually include 10,000 memories.', 3);

    -- Insert installations (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_installations, 'Woven Histories', E'**Artist:** Amara Diallo (b. 1983, Dakar)\n**Year:** 2023\n**Medium:** Reclaimed textiles, gold thread, GPS-traced routes\n**Dimensions:** 500 × 300 cm (wall-mounted tapestry)\n\n---\n\nA monumental tapestry created from clothing donated by immigrant families across five continents. Each piece of fabric carries a documented story of journey, and the gold thread traces actual GPS migration routes.\n\nThe project collected 2,847 clothing items from 214 families over 2 years. QR codes in the gallery link to recorded stories.\n\n*"Every thread is a journey. Every knot is a border crossed."* — Amara Diallo\n\n---\n\n📱 **Interactive:** Scan QR codes to hear donor stories\n🧵 **Materials:** 2,847 fabric pieces from 5 continents\n🗺️ **Gold thread:** Maps GPS routes of actual migrations', NULL, 'Amara Diallo specializes in textile art addressing migration and belonging. Born in Dakar, educated in Paris, now based in London. The project began with her own family''s clothing from their journey from Senegal to France. Gold thread represents value—both monetary and personal—of migration stories. GPS data provided voluntarily by participants. The work cannot be sold—will be donated to a public collection with agreement that all donor stories remain accessible. Partnered with UNHCR to collect some stories from refugee communities. Shortlisted for the Hugo Boss Prize.', 1),
    
    (v_card_id, v_cat_installations, 'Chromatic Meditation', E'**Artist:** Yuki Tanaka (b. 1987, Tokyo)\n**Year:** 2024\n**Medium:** 47 acrylic panels, programmed LED lighting, ambient sound\n**Dimensions:** 600 × 400 × 400 cm (walkthrough installation)\n\n---\n\nA walkthrough installation of translucent colored panels that shift hue throughout the day. Visitors are bathed in ever-changing light, creating a meditative space inspired by Japanese concepts of *ma* (negative space).\n\nThe color program runs on an 8-hour cycle, never repeating exactly. Sound design by composer Ryuichi Sakamoto.\n\n*"Color affects emotion. I wanted to create a space where time slows down."* — Yuki Tanaka\n\n---\n\n🎵 **Sound design:** Ryuichi Sakamoto\n⏱️ **Recommended time:** 10-15 minutes\n🧘 **Tip:** Meditation cushions available inside', NULL, 'Yuki Tanaka creates environments that affect mood and perception. Daughter of a Shinto priest, interested in spiritual architecture. 47 panels reference the 47 prefectures of Japan. LED system uses 1,000 color combinations based on traditional Japanese color names (some dating to 7th century). Sakamoto composed original ambient score before his passing—one of his final collaborations. Temperature maintained at 20°C for optimal contemplation. Research partnership with psychology department studying effects of colored light on stress reduction. Corporate version installed at Google Tokyo headquarters.', 2),
    
    (v_card_id, v_cat_installations, 'Urban Echoes', E'**Artist:** Marcus Webb (b. 1979, Detroit)\n**Year:** 2024\n**Medium:** Found objects, motion sensors, generative sound\n**Dimensions:** Variable (approx. 10 × 8 meters)\n\n---\n\nAn installation using objects found on city streets—shopping carts, traffic cones, discarded furniture—arranged to create an immersive urban soundscape. Sensors detect visitor movement, triggering sounds associated with each object.\n\nAll objects were collected within 5 miles of the gallery over 6 months. Each carries traces of its previous life.\n\n*"Cities throw away more than objects. They throw away stories."* — Marcus Webb\n\n---\n\n🔊 **Interactive:** Your movement triggers different sounds\n📍 **Objects:** All found within 5 miles of gallery\n🗑️ **Note:** Nothing was cleaned—wear marks tell stories', NULL, 'Marcus Webb works with found materials to critique consumer culture and urban displacement. Detroit native, experienced city''s decline firsthand. Objects include: shopping cart from closed grocery store, traffic cones from demolished construction site, furniture from evicted homes. Sound design creates "symphony" from urban noise—car alarms, construction, voices. Motion sensors create unique composition based on how visitors move through space. Webb employs formerly homeless individuals to help collect materials, paying living wage. Part of sales proceeds support Detroit housing justice organizations. Previous version won the Whitney Biennial jury prize.', 3);

    -- Insert into content_templates for template library management
    INSERT INTO content_templates (slug, card_id, scenario_category, is_featured, is_active, sort_order)
    VALUES ('art-gallery-grid', v_card_id, 'cultural', true, true, 1);

    RAISE NOTICE 'Successfully created Art Gallery template with card ID: %', v_card_id;

END $body$;
