-- Cocktail Bar - Grouped Cards Mode (Digital Access)
-- Template: Craft cocktail menu organized by spirit type
-- 
-- INSTRUCTIONS:
-- 1. Replace 'YOUR_USER_ID_HERE' with actual user UUID
-- 2. Update image_url values with actual uploaded image URLs
-- 3. Run this SQL in Supabase SQL Editor or via psql

DO $body$
DECLARE
    v_user_id UUID := 'YOUR_USER_ID_HERE'::UUID;
    v_card_id UUID;
    v_cat_signature UUID;
    v_cat_whiskey UUID;
    v_cat_gin UUID;
    v_cat_agave UUID;
    v_cat_rum UUID;
BEGIN
    -- Insert the card
    INSERT INTO cards (
        id, user_id, name, description, content_mode, is_grouped, group_display, billing_type,
        conversation_ai_enabled, ai_instruction, ai_knowledge_base,
        ai_welcome_general, ai_welcome_item, daily_scan_limit,
        is_access_enabled, access_token
    ) VALUES (
        gen_random_uuid(),
        v_user_id,
        'The Velvet Room - Cocktail Menu',
        E'**Craft cocktails. Timeless classics. New discoveries.**\n\nOur bartenders blend artistry with tradition, creating drinks that honor the classics while pushing boundaries. Every cocktail tells a story.\n\n🥃 Ask your bartender for recommendations based on your mood.',
        'cards',
        true,
        'expanded',
        'digital',
        true,
        'You are a knowledgeable craft bartender with a warm, inviting personality. Help guests find their perfect drink based on flavor preferences (sweet, sour, bitter, spirit-forward), mood, or occasion. Share cocktail history and stories. Be enthusiastic but not pretentious—everyone is welcome regardless of cocktail knowledge.',
        E'The Velvet Room - Craft Cocktail Bar\nEst. 2018 · Named "Best Bar" by City Magazine 2023\n\nHead Bartender: James Monroe (15 years experience, trained in London & Tokyo)\nBar Manager: Sarah Chen (10 years, previously at Death & Co)\n\nBar philosophy: Classic techniques, quality ingredients, personal touch\nIce program: All ice cut in-house from 300lb blocks (takes 3 days to freeze crystal-clear)\nSpirits: 400+ bottles, emphasis on small-batch and craft\n\nSignature technique: Clarified milk punches, fat-washed spirits, barrel-aged cocktails\n\nNon-alcoholic options: Full "Zero Proof" menu available (not just mocktails—serious cocktails without alcohol)\nFood: Light snacks and charcuterie available from our kitchen partner next door\n\nHappy hour: 5-7pm, $10 classic cocktails\nReservations: Recommended for groups of 4+\nDress code: Smart casual (no flip flops)\nPrivate events: Back room seats 20, full buyout available',
        'Welcome to The Velvet Room! I can recommend drinks based on your taste (sweet, sour, strong), explain any cocktail''s ingredients, suggest food pairings, or share the story behind our signatures. What''s your mood tonight?',
        'The "{name}" is excellent! I can describe the flavor profile, list ingredients, suggest similar drinks, or share the cocktail''s history. What would you like to know?',
        1000,
        TRUE,
        replace(replace(encode(gen_random_bytes(9), 'base64'), '+', '-'), '/', '_')
    ) RETURNING id INTO v_card_id;

    -- Create categories by spirit type (Layer 1)
    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '⭐ House Signatures', E'Our bartender''s original creations — each tells a unique story and showcases our house style.\n\n*"These are the drinks we dream about."*', 'Signature cocktails are original creations by our head bartender James. Each underwent months of development and tasting. These drinks showcase our house techniques: clarified milk punch, sous vide infusions, house-made bitters. They change seasonally but favorites stay on permanently. Most profitable for the house—ingredients controlled.', 1)
    RETURNING id INTO v_cat_signature;

    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '🥃 Whiskey & Bourbon', E'Spirit-forward classics and innovative twists for those who appreciate depth and warmth.\n\nOur collection: 100+ bottles from American bourbon to Japanese whisky.', 'Whiskey selection includes: 40 bourbons, 25 ryes, 20 Scotches, 15 Japanese whiskies. Price range $12-45 for cocktails, $15-200 for pours. Staff trained by Whiskey Ambassador program. Ice spheres cut specifically for whiskey service. Can do flights of 3 for comparison tasting. Yamazaki 18 available but limited to 2 pours per night.', 2)
    RETURNING id INTO v_cat_whiskey;

    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '🌿 Gin Cocktails', E'Botanical, refreshing, and versatile — from bright and citrusy to herbaceous and complex.\n\n*Perfect for: Gin lovers, cocktail newcomers, warm weather*', 'Gin selection emphasizes London Dry (Beefeater, Tanqueray), contemporary (Hendrick''s, The Botanist), and New Western (St. George). 35 gins total. Can customize G&Ts with selection of 8 tonics and 12 garnishes. Negroni variations are a specialty. Martini service is tableside with temperature-controlled gin.', 3)
    RETURNING id INTO v_cat_gin;

    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '🌵 Agave Spirits', E'From smooth tequila to smoky mezcal — celebrating Mexico''s finest spirits.\n\n*"Once you go mezcal, you never go back."*', 'Agave program is our pride. 20 mezcals, 15 tequilas, including rare expressions. All 100% agave—no mixto. Direct relationships with small producers in Oaxaca. Can explain the difference between espadín, tobalá, tepeztate. Mezcal tasting flights popular. Educating guests about agave crisis and sustainability.', 4)
    RETURNING id INTO v_cat_agave;

    INSERT INTO content_items (id, card_id, parent_id, name, content, ai_knowledge_base, sort_order)
    VALUES (gen_random_uuid(), v_card_id, NULL, '🏝️ Rum & Tropical', E'Island-inspired refreshers — from light and tropical to dark and complex.\n\n*Close your eyes and you''re on a beach.*', 'Rum selection: 30 bottles spanning Caribbean, Central America, and Pacific. Includes agricole, Spanish-style, English-style. Tropical drinks made with fresh juices (squeezed daily). House orgeat and falernum. Tiki drinks available but done "properly"—balanced, not too sweet. Rum education often needed as guests underestimate the category.', 5)
    RETURNING id INTO v_cat_rum;

    -- Insert signature cocktails (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_signature, 'The Velvet Old Fashioned', E'**Our signature take on the timeless classic**\n\n*Woodford Reserve bourbon · demerara · house bitters · orange oil*\n\n---\n\nWe start with a base of Woodford Reserve, chosen for its rich vanilla and dried fruit notes. House-made demerara syrup (2:1 ratio for extra body) adds depth without cloying sweetness. Our proprietary bitters blend combines Angostura, orange, and house-made walnut bitters.\n\nThe drink is stirred exactly 50 rotations for optimal dilution, served over a hand-cut 2.5-inch ice sphere, and finished with expressed orange oil and a flamed orange peel.\n\n---\n\n🥃 **Spirit:** Bourbon\n📊 **Strength:** Strong (2oz pour)\n🍬 **Profile:** Spirit-forward, subtly sweet, aromatic\n\n**$16**', NULL, 'Our #1 selling cocktail since opening. House bitters recipe took 6 months to develop—walnut adds subtle earthiness. Demerara syrup uses Demerara sugar from Guyana. Ice sphere takes 3 days to freeze and 2 minutes to cut. Can substitute: Rittenhouse Rye (spicier), Nikka Coffey Grain (smoother). Named after the bar—the drink that defines us. James developed this during his time in Tokyo studying Japanese bartending precision.', 1),
    
    (v_card_id, v_cat_signature, 'Smoke & Mirrors', E'**A theatrical experience for mezcal lovers**\n\n*Del Maguey Vida mezcal · Aperol · lime · agave · chipotle*\n\n---\n\nOur most dramatic cocktail: smoky mezcal meets bitter Aperol, brightened with fresh lime and rounded with raw agave nectar. A whisper of house-made chipotle tincture adds warmth without overwhelming heat.\n\nServed under a glass cloche filled with applewood smoke—lifted tableside for full sensory impact. The smoke mingles with the drink and dissipates within moments, leaving behind subtle aromatics.\n\n---\n\n🥃 **Spirit:** Mezcal\n📊 **Strength:** Medium-Strong\n🍬 **Profile:** Smoky, bitter-sweet, complex\n\n**$18**\n\n📸 *One of our most Instagrammed drinks*', NULL, 'Del Maguey Vida chosen for balance of smoke and fruit—not too aggressive. Chipotle tincture made in-house: dried chipotles steeped in high-proof vodka for 2 weeks, then strained. Use sparingly—2 drops max. Applewood smoke from chips using a PolyScience smoking gun. Cloche creates drama and captures aroma. Best consumed within 2 minutes of reveal for full smoke experience. Inspired by Oaxacan mezcalerias where smoke is everywhere.', 2),
    
    (v_card_id, v_cat_signature, 'Lavender Dreams', E'**Floral elegance in a glass**\n\n*Grey Goose vodka · house lavender syrup · St-Germain · lemon · egg white*\n\n---\n\nA silky, aromatic cocktail that balances floral sweetness with bright citrus. We steep French lavender in simple syrup for 24 hours, then combine with premium vodka, elderflower liqueur, fresh lemon, and egg white for a luxurious foam.\n\nDry shaken first (no ice) for foam structure, then wet shaken to chill. Served in a chilled coupe with a single lavender sprig.\n\n---\n\n🥃 **Spirit:** Vodka\n📊 **Strength:** Medium\n🍬 **Profile:** Floral, creamy, elegant\n\n**$16**\n\n🌿 *Can be made vegan with aquafaba*', NULL, 'Most popular with guests who say they "don''t like cocktails." Lavender sourced from Provence, same farm supplies L''Occitane. Too much lavender tastes like soap—we use exactly 2 tablespoons per batch of syrup. Egg white from pasteurized eggs for safety. Aquafaba (chickpea water) is perfect vegan substitute—guests can''t tell the difference. Grey Goose chosen for its clean profile that doesn''t compete with florals.', 3);

    -- Insert whiskey cocktails (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_whiskey, 'Tokyo Sour', E'**East meets West in a glass**\n\n*Suntory Toki · yuzu · egg white · shiso · matcha dust*\n\n---\n\nA Japanese-inspired whisky sour featuring Suntory Toki (a blend designed for mixing), fresh yuzu juice imported from Japan, and silky egg white foam. Aromatic shiso leaf adds an herbaceous, slightly minty note.\n\nThe drink is dry shaken first for foam, then wet shaken with ice. Finished with a delicate dusting of ceremonial-grade matcha from Uji, Kyoto.\n\n---\n\n🥃 **Spirit:** Japanese Whisky\n📊 **Strength:** Medium\n🍬 **Profile:** Citrus-forward, creamy, aromatic\n\n**$17**\n\n🌿 *Can be made vegan with aquafaba*', NULL, 'Created by head bartender James after his training trip to Tokyo in 2019. Yuzu juice is 10x price of lemon but irreplaceable—nothing else has that floral citrus quality. Shiso (perilla) leaf from local Japanese grocery. Matcha is ceremonial grade (about $30/oz)—culinary grade is too bitter. Suntory Toki was designed as a mixing whisky—smooth, approachable, plays well with citrus. Very popular with Japanese whisky curious guests.', 1),
    
    (v_card_id, v_cat_whiskey, 'Midnight Manhattan', E'**Dark, brooding, sophisticated**\n\n*Rittenhouse Rye · Carpano Antica · Cynar · Luxardo cherry*\n\n---\n\nOur twist on the classic Manhattan adds Cynar (an artichoke-based amaro) for earthy depth and intriguing complexity. Rittenhouse Rye at 100 proof stands up to the rich sweet vermouth, while the Cynar adds a subtle bitter-vegetal note.\n\nStirred exactly 50 rotations until silky, strained into a chilled coupe, and garnished with a single Luxardo cherry that''s worth the import cost.\n\n---\n\n🥃 **Spirit:** Rye Whiskey\n📊 **Strength:** Strong\n🍬 **Profile:** Spirit-forward, complex, slightly bitter\n\n**$17**\n\n*"A Manhattan for people who find Manhattans boring."*', NULL, 'Rittenhouse 100 proof is bartender''s choice for Manhattan variations—high proof means flavor isn''t buried. Carpano Antica is the gold standard of sweet vermouth ($40/bottle vs $10 for Martini). Cynar adds artichoke-based earthiness that rounds out sweetness. Luxardo cherries ($25/jar) are essential—maraschinos are banned from this bar. Named Midnight because of the dark, mysterious quality. James'' personal favorite after a long shift.', 2),
    
    (v_card_id, v_cat_whiskey, 'Penicillin', E'**The modern classic that cures what ails you**\n\n*Monkey Shoulder blended Scotch · lemon · honey-ginger · Laphroaig float*\n\n---\n\nInvented in 2005 by Sam Ross at Milk & Honey, the Penicillin has already earned its place among the classics. A blended Scotch base with homemade honey-ginger syrup (we cook fresh ginger into raw honey), fresh lemon, and a dramatic float of peaty Laphroaig.\n\nThe float hits your nose before your lips—smoke announces the drink before you taste it.\n\n---\n\n🥃 **Spirit:** Scotch Whisky\n📊 **Strength:** Medium-Strong\n🍬 **Profile:** Sweet, smoky, warming\n\n**$16**\n\n*Often ordered by Scotch skeptics who discover they love it*', NULL, 'Sam Ross created this at Milk & Honey NYC—one of the most influential bars of the 21st century. Honey-ginger syrup made weekly: fresh ginger cooked into honey (1:1) for 30 minutes. Monkey Shoulder is a blend of 3 Speyside malts—smooth, approachable, designed for mixing. Laphroaig float (1/4 oz) adds dramatic peat smoke aroma. Not stirred in—layered on top. Great cold remedy (though not medical advice!). We''ve converted many Scotch skeptics with this drink.', 3),
    
    (v_card_id, v_cat_whiskey, 'Paper Plane', E'**Equal parts everything—perfectly balanced**\n\n*Bourbon · Aperol · Amaro Nonino · lemon*\n\n---\n\nThe Paper Plane proves that equal parts can create perfect harmony. Four ingredients, each playing their role: bourbon''s warmth, Aperol''s bitter orange, Amaro Nonino''s honey-herb complexity, lemon''s brightness.\n\nCreated in 2007 by Sam Ross (also creator of the Penicillin), named after the M.I.A. song playing when he made it.\n\n---\n\n🥃 **Spirit:** Bourbon\n📊 **Strength:** Medium\n🍬 **Profile:** Bittersweet, complex, balanced\n\n**$16**\n\n*No garnish needed—the drink speaks for itself*', NULL, 'Another Sam Ross creation (Violet Hour, Chicago). Equal parts (3/4 oz each) is the key—changing ratios throws off balance. Amaro Nonino has honey and herb notes unavailable in other amari. Named when M.I.A.''s "Paper Planes" came on the bar speakers. Shaken hard with ice, strained into coupe. No garnish by design—Ross believed the drink was complete. Popular with amaro lovers discovering bourbon, and bourbon lovers discovering amaro. Gateway drink to the bitter world.', 4);

    -- Insert gin cocktails (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_gin, 'Garden Party', E'**Summer in a glass, any time of year**\n\n*Hendrick''s gin · elderflower · cucumber · lemon · prosecco*\n\n---\n\nA spritz-style cocktail that''s light, floral, and impossibly refreshing. Hendrick''s gin provides the cucumber-rose base, lifted with St-Germain elderflower liqueur and brightened with fresh lemon. Topped with prosecco for effervescence.\n\nBuilt over ice, stirred gently, garnished with a ribbon of fresh cucumber.\n\n---\n\n🥃 **Spirit:** Gin\n📊 **Strength:** Light (easy drinking)\n🍬 **Profile:** Floral, refreshing, effervescent\n\n**$15**\n\n*Our most popular brunch cocktail*', NULL, 'Hendrick''s chosen for its cucumber and rose notes—complements rather than competes with elderflower. St-Germain elderflower liqueur (the "bartender''s ketchup" because it goes with everything). Fresh cucumber ribbon as garnish—essential for aroma. Prosecco added last to preserve bubbles. Can substitute Sipsmith for more juniper-forward version, or Aviation for more floral. Very popular with gin lovers and cocktail newcomers alike. Outsells mimosas at brunch 3:1.', 1),
    
    (v_card_id, v_cat_gin, 'Honey Bee', E'**Sweet sophistication with a botanical twist**\n\n*Beefeater gin · local honey · lavender · lemon*\n\n---\n\nA Bee''s Knees (the Prohibition-era classic) upgraded with house-made lavender tincture. Local wildflower honey brings floral sweetness that changes with the seasons, while the lavender adds aromatic complexity without overwhelming.\n\nShaken, strained, served up with a dried lavender sprig.\n\n---\n\n🥃 **Spirit:** Gin\n📊 **Strength:** Medium\n🍬 **Profile:** Sweet, floral, balanced\n\n**$15**\n\n*Popular with guests who find gin "too juniper-y"*', NULL, 'Honey from local apiary 20 miles north—changes seasonally (currently clover, spring is wildflower, fall is buckwheat). Lavender tincture uses culinary lavender steeped for 1 week—only 3 drops per drink or it tastes like soap. The Bee''s Knees was invented during Prohibition to mask bathtub gin. We use Beefeater for its botanical balance—juniper present but not aggressive. Popular with guests transitioning from vodka to gin. The honey sweetness eases them in.', 2),
    
    (v_card_id, v_cat_gin, 'The Last Word', E'**Equal parts, bold complexity**\n\n*Gin · Green Chartreuse · Maraschino · lime*\n\n---\n\nA pre-Prohibition classic from the Detroit Athletic Club, lost for decades until resurrected by Murray Stenson in Seattle. Four equal parts create an improbably harmonious whole—herbaceous, sweet, tart, and spirit-forward.\n\nGreen Chartreuse (130 herbs, made by monks) does the heavy lifting, balanced by maraschino''s cherry sweetness and lime''s brightness.\n\n---\n\n🥃 **Spirit:** Gin\n📊 **Strength:** Strong\n🍬 **Profile:** Herbaceous, complex, bold\n\n**$17**\n\n*"The bartender''s handshake—order this and we know you''re serious."*', NULL, 'Pre-Prohibition recipe from Detroit Athletic Club (1920s), lost until Murray Stenson found it in an old book and revived it at Zig Zag Café Seattle (2004). Green Chartreuse is made by Carthusian monks from 130 herbs—recipe known by only 2 monks at a time. Luxardo Maraschino is different from cherry liqueur—it''s made from Marasca cherries, pit and all. Equal parts (3/4 oz each) is essential. Very spirit-forward—know your guest before recommending. Bartender handshake: order this and we know you know cocktails.', 3);

    -- Insert agave cocktails (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_agave, 'Oaxacan Negroni', E'**A smoky twist on the Italian classic**\n\n*Del Maguey Vida mezcal · Campari · Carpano Antica*\n\n---\n\nThe classic Negroni reimagined with mezcal instead of gin. The smokiness of the mezcal adds incredible depth to the bitter-sweet balance, creating something that feels both familiar and entirely new.\n\nEqual parts stirred, served over a large ice cube, garnished with an expressed orange twist.\n\n---\n\n🥃 **Spirit:** Mezcal\n📊 **Strength:** Strong\n🍬 **Profile:** Bitter, smoky, complex\n\n**$16**\n\n*"The drink that converted me to mezcal."* — approximately 100 guests', NULL, 'Phil Ward (Death & Co) is often credited with popularizing this variation. Del Maguey Vida chosen for smoke that enhances rather than overwhelms. Campari''s bitter orange loves the smoky backdrop. Carpano Antica (premium sweet vermouth) adds vanilla and spice notes. Large ice cube (cut from 300lb block) for slow dilution—this drink improves as it opens up. Orange twist expressed over drink to release oils. One of our most successful "conversion" drinks—turns mezcal skeptics into believers.', 1),
    
    (v_card_id, v_cat_agave, 'Mezcal Mule', E'**Smoke meets spice**\n\n*Del Maguey Vida · house ginger beer · lime · sal de gusano rim*\n\n---\n\nOur take on the Moscow Mule swaps vodka for mezcal and amps up the ginger. House-made ginger beer (2 lbs fresh ginger per batch) brings serious heat that plays beautifully against the smoke.\n\nServed in a copper mug with a sal de gusano (worm salt) half-rim for those who want it.\n\n---\n\n🥃 **Spirit:** Mezcal\n📊 **Strength:** Medium\n🍬 **Profile:** Smoky, spicy, refreshing\n\n**$15**\n\n*The ginger beer has serious heat—we can dial it back on request*', NULL, 'House ginger beer made weekly: 2 lbs fresh ginger, sugar, water, champagne yeast. Ferments for 48 hours—much spicier than commercial. Sal de gusano is traditional Oaxacan seasoning—dried maguey worms, chilies, salt ground together. Sounds scary, tastes amazing. Copper mug keeps drink colder longer. Can reduce ginger heat by mixing with commercial ginger beer. Good entry point for mezcal curious—the ginger provides familiar comfort.', 2);

    -- Insert rum cocktails (Layer 2)
    INSERT INTO content_items (card_id, parent_id, name, content, image_url, ai_knowledge_base, sort_order) VALUES
    (v_card_id, v_cat_rum, 'Dark & Stormy', E'**The perfect storm of rum and ginger**\n\n*Gosling''s Black Seal rum · house ginger beer · lime*\n\n---\n\nThe official drink of Bermuda, made with the only rum legally allowed to be called a Dark & Stormy: Gosling''s Black Seal. Our house-made ginger beer has serious heat—not for the faint-hearted.\n\nLayered (not stirred) for visual drama—the rum floats on top like a storm cloud.\n\n---\n\n🥃 **Spirit:** Dark Rum\n📊 **Strength:** Medium\n🍬 **Profile:** Spicy, sweet, bold\n\n**$14**\n\n*Gosling''s trademarked the name—it''s the only legally protected cocktail*', NULL, 'Gosling''s has trademark on "Dark & Stormy" name—must use their rum. House ginger beer made fresh weekly with 2lbs fresh ginger per batch. Much spicier than commercial. Layered, not stirred—rum floats on top for visual effect and first-sip punch. The "storm" effect when you stir it yourself. Lime wedge essential for balance. Can reduce ginger heat on request by mixing with commercial. Popular with people who think they don''t like rum—the ginger does the talking.', 1),
    
    (v_card_id, v_cat_rum, 'Jungle Bird', E'**Tiki meets Italian bitter**\n\n*Blackstrap rum · Campari · pineapple · lime · simple syrup*\n\n---\n\nCreated at the Kuala Lumpur Hilton in 1978, the Jungle Bird bridges tiki and the bitter cocktail world. Funky Blackstrap rum meets Campari''s bitter orange, with tropical pineapple and lime keeping things bright.\n\nShaken hard, served over crushed ice, garnished with pineapple frond.\n\n---\n\n🥃 **Spirit:** Rum\n📊 **Strength:** Medium\n🍬 **Profile:** Tropical, bitter, funky\n\n**$15**\n\n*"The drink that taught me rum could be complex."*', NULL, 'Created in 1978 at KL Hilton, forgotten for decades, revived by Giuseppe González at Dutch Kills (NYC). Blackstrap rum (Cruzan or Plantation) has molasses-heavy, almost burnt sugar quality. Campari seems odd with tropical flavors but works perfectly—the bitter balances the sweet. Fresh pineapple juice essential (never canned). Crushed ice dilutes faster—intended for quick drinking before it waters down. Gateway drink to both tiki and amaro worlds.', 2),
    
    (v_card_id, v_cat_rum, 'Hemingway Daiquiri', E'**The writer''s favorite, perfected**\n\n*White rum · lime · grapefruit · Luxardo Maraschino*\n\n---\n\nErnest Hemingway supposedly drank these by the pitcher at El Floridita in Havana. Our version honors the original: white rum, fresh lime, pink grapefruit, and just enough Maraschino for complexity.\n\nDouble-strained into a chilled coupe, served bone-dry as Hemingway preferred.\n\n---\n\n🥃 **Spirit:** White Rum\n📊 **Strength:** Medium\n🍬 **Profile:** Tart, complex, refreshing\n\n**$15**\n\n*"A daiquiri for people who think daiquiris are too sweet."*\n\n🩸 Also called "Papa Doble" (double) because Hemingway drank them large', NULL, 'Hemingway was diabetic—he asked for daiquiris without sugar, double rum, extra lime. Constantino Ribalaigua at El Floridita added grapefruit and Maraschino to balance. Our version uses fresh Ruby Red grapefruit. Served "bone-dry" means no added sugar—the Maraschino provides enough sweetness. Luxardo Maraschino is made from whole cherries including pit—dry, not sweet like cherry liqueur. Often surprises guests expecting a sweet frozen drink. We''ve successfully converted many daiquiri skeptics.', 3);

    -- Insert into content_templates for template library management
    INSERT INTO content_templates (slug, card_id, venue_type, is_featured, is_active, sort_order)
    VALUES ('cocktail-bar', v_card_id, 'food', true, true, 7);

    RAISE NOTICE 'Successfully created Cocktail Bar template with card ID: %', v_card_id;

END $body$;
