#!/bin/bash

# =============================================================================
# Prepare Templates SQL Script
# =============================================================================
# This script combines all content template SQL files and replaces the
# placeholder user ID with the actual user ID you provide.
#
# The output can be run directly in Supabase SQL Editor.
#
# Usage:
#   ./scripts/prepare-templates-sql.sh
#
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Directory containing template SQL files
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TEMPLATES_DIR="$PROJECT_ROOT/content_templates/sql"
OUTPUT_FILE="$PROJECT_ROOT/content_templates/templates_ready_to_run.sql"

echo -e "${CYAN}"
echo "=============================================="
echo "  Content Templates SQL Preparation Script"
echo "=============================================="
echo -e "${NC}"

# Check if templates directory exists
if [ ! -d "$TEMPLATES_DIR" ]; then
    echo -e "${RED}Error: Templates directory not found at $TEMPLATES_DIR${NC}"
    exit 1
fi

# Count template files
TEMPLATE_COUNT=$(ls -1 "$TEMPLATES_DIR"/*.sql 2>/dev/null | wc -l | tr -d ' ')

if [ "$TEMPLATE_COUNT" -eq 0 ]; then
    echo -e "${RED}Error: No SQL template files found in $TEMPLATES_DIR${NC}"
    exit 1
fi

echo -e "${BLUE}Found ${TEMPLATE_COUNT} template files:${NC}"
echo ""
for file in "$TEMPLATES_DIR"/*.sql; do
    if [ -f "$file" ]; then
        filename=$(basename "$file" .sql)
        echo "  • $filename"
    fi
done
echo ""

# Prompt for user ID
echo -e "${YELLOW}Enter the User ID (UUID) to own these templates:${NC}"
echo -e "${CYAN}(You can find your user ID in Supabase Dashboard → Authentication → Users)${NC}"
echo ""
read -p "User ID: " USER_ID

# Validate UUID format (basic validation)
UUID_REGEX='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
if [[ ! $USER_ID =~ $UUID_REGEX ]]; then
    echo -e "${RED}Error: Invalid UUID format.${NC}"
    echo "Expected format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    exit 1
fi

echo ""
echo -e "${GREEN}✓ Valid UUID: $USER_ID${NC}"
echo ""

# Ask which templates to include
echo -e "${YELLOW}Which templates would you like to include?${NC}"
echo ""
echo "  1) All templates ($TEMPLATE_COUNT files)"
echo "  2) Select specific templates"
echo ""
read -p "Choice [1]: " CHOICE
CHOICE=${CHOICE:-1}

SELECTED_FILES=()

if [ "$CHOICE" == "2" ]; then
    echo ""
    echo -e "${BLUE}Enter template numbers (space-separated) or 'all':${NC}"
    echo ""
    
    # List templates with numbers
    i=1
    declare -A FILE_MAP
    for file in "$TEMPLATES_DIR"/*.sql; do
        if [ -f "$file" ]; then
            filename=$(basename "$file" .sql)
            echo "  $i) $filename"
            FILE_MAP[$i]="$file"
            ((i++))
        fi
    done
    echo ""
    
    read -p "Selection: " SELECTION
    
    if [ "$SELECTION" == "all" ]; then
        for file in "$TEMPLATES_DIR"/*.sql; do
            SELECTED_FILES+=("$file")
        done
    else
        for num in $SELECTION; do
            if [ -n "${FILE_MAP[$num]}" ]; then
                SELECTED_FILES+=("${FILE_MAP[$num]}")
            else
                echo -e "${RED}Warning: Invalid selection '$num' ignored${NC}"
            fi
        done
    fi
else
    for file in "$TEMPLATES_DIR"/*.sql; do
        if [ -f "$file" ]; then
            SELECTED_FILES+=("$file")
        fi
    done
fi

if [ ${#SELECTED_FILES[@]} -eq 0 ]; then
    echo -e "${RED}Error: No templates selected${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}Selected ${#SELECTED_FILES[@]} template(s)${NC}"
echo ""

# Create output file
echo -e "${YELLOW}Generating combined SQL file...${NC}"
echo ""

cat > "$OUTPUT_FILE" << 'HEADER'
-- =============================================================================
-- CONTENT TEMPLATES - Combined SQL
-- =============================================================================
-- Generated by prepare-templates-sql.sh
-- 
-- This file contains all content template inserts ready to run.
-- 
-- INSTRUCTIONS:
-- 1. Copy this entire file
-- 2. Open Supabase Dashboard → SQL Editor
-- 3. Paste and run
--
-- IMPORTANT: Each template is wrapped in a transaction. If one fails,
-- it won't affect the others.
-- =============================================================================

HEADER

echo "-- Generated: $(date)" >> "$OUTPUT_FILE"
echo "-- User ID: $USER_ID" >> "$OUTPUT_FILE"
echo "-- Templates: ${#SELECTED_FILES[@]}" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Process each template
SUCCESS_COUNT=0
for file in "${SELECTED_FILES[@]}"; do
    filename=$(basename "$file" .sql)
    echo "  Processing: $filename"
    
    echo "" >> "$OUTPUT_FILE"
    echo "-- ============================================" >> "$OUTPUT_FILE"
    echo "-- Template: $filename" >> "$OUTPUT_FILE"
    echo "-- ============================================" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # Read file and replace placeholder
    sed "s/YOUR_USER_ID_HERE/$USER_ID/g" "$file" >> "$OUTPUT_FILE"
    
    echo "" >> "$OUTPUT_FILE"
    
    ((SUCCESS_COUNT++))
done

echo ""
echo -e "${GREEN}=============================================="
echo "  ✓ SQL File Generated Successfully!"
echo "=============================================="
echo -e "${NC}"
echo ""
echo -e "Output file: ${CYAN}$OUTPUT_FILE${NC}"
echo ""
echo "Total templates: $SUCCESS_COUNT"
echo "User ID: $USER_ID"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "  1. Open the generated file:"
echo -e "     ${CYAN}cat $OUTPUT_FILE${NC}"
echo ""
echo "  2. Copy the contents"
echo ""
echo "  3. Go to Supabase Dashboard → SQL Editor"
echo ""
echo "  4. Paste and click 'Run'"
echo ""
echo -e "${GREEN}Or run directly with Supabase CLI:${NC}"
echo -e "     ${CYAN}supabase db execute --file $OUTPUT_FILE${NC}"
echo ""


